runtime: python39
entrypoint: gunicorn -b :$PORT base.wsgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: "base.settings"
  SECRET_KEY: "django-insecure-ga%fj-dijxl(jgdwnfo7&6m9f9#^yaorxy-!*&e6s(=bim%3e*"
  DB_NAME: "test_vs_01"
  DB_USER: "root"
  DB_PASSWORD: "asdasdasd"
  DB_HOST: "35.204.160.67"

handlers:
  - url: /static
    static_dir: static/

  - url: /_ah/warmup
    script: auto
    secure: always

  - url: /.*
    script: auto
