runtime: python39  # Укажите версию Python
entrypoint: gunicorn -b :$PORT base.wsgi  # Укажите путь до WSGI вашего приложения

# Опциональные настройки масштабирования
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 5

# Пути для обработки запросов
handlers:
  - url: /.*
    script: auto
