runtime: python39
entrypoint: gunicorn -b :$PORT base.wsgi  # Общий WSGI файл в каталоге base

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 5

handlers:
  - url: /api/.*
    script: auto
